spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: <YOUR_CLEIENT_ID>
            clientSecret: <YOUR_CLIENT_SECRET>
            scope: read:user
