spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23li3tHTnIbBPijtYA
            clientSecret: a711cc82df956ab08583a9a3982ccd75872c28ef
            scope: read:user
